name: PR Merged
on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]
permissions:
  contents: write
jobs:
  call-tests:
    name: Test
    uses: ./.github/workflows/tests.yml

  call-docker-build:
    name: Build
    uses: ./.github/workflows/docker_build_push.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      # platforms: linux/arm/v8
      tags: ${{ github.base_ref }},"master"
